tasks:
<<<<<<< HEAD
  - init: gradle init
    command: gradle bootRun
ports:
  - port: 8080
    onOpen: open-preview
github:
  prebuilds:
    # enable prebuilds for all branches in this repo
    branches: true
=======
  - init: mvn install -DskipTests=false
image:
  file: .gitpod.Dockerfile
>>>>>>> f89049edeff378200b5455fe39554a1f0d24ff5c
